algorithms :
  "anon_etaamb":
    params:
      - "lang"
    env_required:
      - "ANON_ETAAMB_HOST"
  "anon_test":
    params: []
    env_required: []
  "anon_trazor":
    params: []
    env_required: []
  "anon_bert":
    params: []
    env_required: 
      - "ANON_BERT_HOST"
